### ISSUE TITLE
11/2 Weekly Conference call : 머신 러닝의 기본 요소

### ISSUE THREAD

**Issue by ProtossDragoon** [sju-coml/SAI-2020-Team-I#15]
- [x] 장후
- [x] 주희
- [x] 우혁
- [x] 영채

**Comment by ProtossDragoon** [comment]
- [x] 사랑을 담은 결석자 전화

### 시작하기 전
- [x] 녹화 환경 준비

### Notion
- [x] 그룹장 분들로부터 notion 활용중인 내용 들어보기

### 발표
- chapter 4
- [x] 케라수요일3시
- [x] 트리케라톱수

<hr>

### 공지
- [x] (그동안 발표가 너무 널널했지요!) Filter 관련 이론 + 실습 이해하기 : 제가 제공해 드리는 자료 그대로 사용해서, 발표하기 (한팀은 책발표, 한팀은 흥미로운 주제 발표 대신 이거 발표를 합니다.) 한 사람 기준, 80% 이상 숙지하는 것에 7시간정도 걸릴 것 같으니, 시간을 넉넉히 투자하세요! 그리고 chapter 5 는 한방에 모두 진행하기가 어려울 것 같아요. 두 주에 나눠서 진행합니다.
  - [x] 아래 제시된 주제들 : 트리케라톱수 / 요구되는 퀄리티 : 제가 첨부한 PPT 만큼.
  - [ ] chapter 5 (5-1 ~ 5-3) : 1조 다음은 2조

<br>
<br>

**제시된 주제**

<br>

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/46595649/97804033-92e0b380-1c90-11eb-8cb5-818ddcf951cf.png">


<br>

<img width="958" alt="image" src="https://user-images.githubusercontent.com/46595649/97804024-89efe200-1c90-11eb-8754-f9c280d2ddd4.png">


<br>

- [x] OKR 재언급
  - [x] OKR 에 대해서 찾아보고, 팀별로 알아본 내용을 notion 및 GitHub 에 업로드하기.
- [x] 팀별 업무 분배 이야기
  - [x] 한명씩 맡아가면서 공부하지 마시고, 다같이 집단지성으로 공부하시길 바랄게요. 따로 만나는 날을 정하는 것도 좋지만, 상시로 meet 등을 활용해서 공동공부를 하세요. 가령, OKR 을 한 분이 맡아서 하고, 한 분은 발표를 맡아서 하고 - 이런 식으로 하면, 뒷쪽으로 가서 발표 안 맡으신 분들은 큰일 납니다. 정말 큰일 나요!
  - [x] 다음번에 트리케라톱수 팀만 발표한다고, 그분들만 준비하면 되는 게 아니라, 개별적으로 다 해보셔야 합니다. 그렇지 않으면 "연결이 안 돼요!!". 발표를 하는 것의 취지는 그주의 공부를 그분들께 맡기는 것이 아니라, 공부를 하고 있다는 상황을 공유하기 위함입니다.
  - [x] 모르는 것은 반드시 issue 올려서 공유해 주세요.

<br>

<hr>

### 각자 공부해야 하는 것 정리
- [ ] OKR 에 대해서 조사
- [ ] **제시된 주제** : 발표담당이 아니더라도 개인적으로 PPT 를 만들어보면서 정리하기를 추천합니다. 그렇게 하면 대충 안 넘어가게 됩니다.
- [ ] 책 5-1 ~ 5-3 까지 

<br>

### 업로드하거나 공개적으로 준비해야 하는 것 정리
- OKR 공부내용
  - [x] 그룹별로 Github Issue 에, OKR 라벨 붙여서.
  - [x] 그룹별로 Notion에
- [x] 책 발표하는 팀 : 5-1 ~ 5-3 까지 PPT (약 6~9시간)
- [x] 제시된 주제 발표하는 팀 : 저 위에 올라가 있는 내용 전부 PPT 및 Source Code (약 7~12시간)
  - [이정도 퀄리티까지 준비](https://github.com/ProtossDragoon/Deep-Learning-with-Python)
- [x] 간단한 프로젝트 소개
  - [x] https://github.com/ProtossDragoon/MAiEye
  - [x] https://github.com/lunaB/Project-Heami
  - [x] https://www.youtube.com/channel/UCMf5F1uTcuz8MPN62kb55cg?view_as=subscriber -> 흥미를 끄는...
  - [x] https://youtu.be/eLTLtUVuuy4
  - [x] https://fluxml.ai/experiments/styleTransfer/
  - [x] https://github.com/yoonseok312/watch-out
  - [x] https://github.com/yunho0130/tensorflow-lite
  - [x] https://youtu.be/fslA0nMQbbs?t=892

**Comment by moonk1212** [comment]
#### chapter 4 문의 사항
상황: 1조다음은2조에서 스터디 하던 중  가중치 규제 추가 라는 부분에 대해서 얘기 나누던중 
가중치 규제 추가가 네트워크 복잡도에 제한을 두어 가중치가 작은 값을 가지도록 강제한다는 것은 알게 됨 
문제: 네트워크 복잡도와 가중치 규제가 정확히 어떤 차이가 있는지 모르겠음 
L1규제와 L2 규제에 대한 부분이 정확히 이해가 안되는 상황이 발생함
