### ISSUE TITLE
11/16 Weekly Conference call : 합성곱 신경망 (2 of 2)

### ISSUE THREAD

**Issue by ProtossDragoon** [sju-coml/SAI-2020-Team-I#21]
- [x] 사랑을 담은 결석자 전화

### 시작하기 전

- [x] 녹화 환경 준비

### 간단한 점검

- [x] 그룹장 분들~ 프로젝트 주제 issue 올렸어요?
- [x] 프로젝트 제안서 제출 - ISSUE 에 올 ! 리 ! 세 ! 요 ! 제발 올려주세요.
- [x] 프로젝트에 대해서 주제만 간단히 이야기해보기. 자세한 이야기는 잠시 후에~

### 발표

- [x] 제시된 주제들 : 1조 다음은 2조
- [x] chapter 5 나머지 : 케라수요일 3시

<hr>

### 공지

- [x] (그동안 발표가 너무 널널했지요! 시리즈의 마지막!) 다음 주제는 CAM 과 GRAD-CAM 과 관련된 내용입니다! 만약, 지금까지 제가 제시해 드린 컨셉들을 정확히 이해하고자 노력하셨다면 1주라는 시간에서도 충분히 어느정도 이해해내실 수 있는 과제일 것입니다. 또한, 오늘 발표하신 5-4 가 이와 비슷한 내용입니다. *제가 항상 자기 발표 아니더라도 열심히 준비하기를 부탁드렸지요..!*
  - [x] 제시된 주제 파헤치기 : 케라수요일 3시
  - [x] chapter 6 : 트리케라톱수

<br>
<br>

**제시된 주제**

Class Activation Map 이 무엇인지 조사하기. 특히, 각 Filter 들이 무슨 의미를 가지고 어떤 일이 일어나는지 이해하기.
GRAD CAM 에 대해서 조사하고, Class Activation Mapping 과의 어떤 차이점이 있는지 공부해 보기

<img width="629" alt="image" src="https://user-images.githubusercontent.com/46595649/99252719-be4bcc80-2852-11eb-8a68-306094bfcc62.png">

참고자료 : 제가 올린거 있습니다. https://www.youtube.com/channel/UCMf5F1uTcuz8MPN62kb55cg?view_as=subscriber
유튜브를 적극 추천합니다.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/46595649/99253496-323aa480-2854-11eb-91d2-f7a189624440.png">

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/46595649/99253449-1fc06b00-2854-11eb-9936-b47b48f60b36.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/46595649/99252774-d7547d80-2852-11eb-9609-81ea4b2541c0.png">

<br>

### 프로젝트

- [x] 프로젝트 주제 한팀씩 이야기하고 이에 대해서 논의해보기 (혹시 마이크를 킬 수 있는 사람이 없다면 그냥 문서만 확인합니다.)
  - [x] 발표 : 트리케라톱스
  - [x] 발표 : 1조 다음은 2조
  - [x] 발표 : 케라수요일3시

### 프로젝트 가이드 
- [x] 발표 : @lunaB 의 end-to-end 프로젝트 show show show time ~
- [x] 발표 : @lunaB 의 kaggle 대회 참가부터 제출까지

<br>

### OKR

- [x] (시간적 여유가 있다면) 제꺼 공유
- [x] 안내 : 우선 운영진끼리 먼저 공유한 후, 캘린더를 공유하겠습니다. 장장 프로젝트 발표일까지 가게 되는 기나긴 여정이 될 것 같습니다.

<hr>

### 각자 공부해야 하는 것 정리

- [x] 프로젝트 주제에 대한 고민과 1차 결정
- [x] **제시된 주제** : 발표담당이 아니더라도 개인적으로 PPT 를 만들어보면서 정리하기를 추천합니다. 그렇게 하면 대충 안 넘어가게 됩니다. 꼭이요. 
- [x] 책 chapter 6 

<br>

### 업로드하거나 공개적으로 준비해야 하는 것 정리

- 1. 프로젝트 관련
  - [x] 프로젝트 주제를 재설계하고자 하는 팀 : 주제 다시 정해서 정리하기
  - [x] 프로젝트가 어디까지 진행되었는가 : 추가적으로 1주간 진행한 내용 공유
- 2. 발표 관련
  - [x] 책 발표하는 팀 : chapter 6 PPT (약 6~9시간)
  - [x] 제시된 주제 발표하는 팀 : CAM & GRAD-CAM (약 15시간)
- 3. OKR 관련
  - [x] 각 개인의 OKR 을 정확히 어디엔가 적어 두기 (어느정도 정해 오시면 같이 이야기할 때 더 유익하기 때문)

**Comment by ProtossDragoon** [comment]
http://cs231n.stanford.edu/slides/2017/cs231n_2017_lecture4.pdf

**Comment by ProtossDragoon** [comment]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/46595649/99284095-3200d000-2879-11eb-9085-e0b3cd54a3c8.png">

**Comment by lunaB** [comment]
새벽 2시넘게 같이 공부에 참여해주신 모두에게 감사,,,
오늘 제가 발표한 프로젝트 가이드 코드입니다. 프로젝트 하는데 도움이 되면 좋겠습니다.
https://github.com/lunaB/keras-tfjs-mnist-example
