### ISSUE TITLE
12/28 Weekly Conference call : 프로젝트 집중 

### ISSUE THREAD

**Issue by lunaB** [sju-coml/SAI-2020-Team-I#26]
- [x] 슬쩍 걸어보는 결석자 전화

### 시작하기 전
- [x] 녹화 환경 준비

### 결정 확인
- OKR 추가 신청
- 프로젝트 발표회는 1/4 월 밤 11시 오프라인으로 진행 할 예정이였으나 코로나로 인하여 상황이 어려워 보입니다. 우선 지켜보도록 하겠습니다.

<br>
<br>

### 컨텐츠 요약
- 현재 책은 2챕터를 남겨두고 있으며 마지막 챕터는 요약 챕터입니다.
- 이번주는 프로젝트 집중 주간이라 주제 발표를 하지 않습니다.
- 우혁님의 예정된 코드리뷰 세션이 있겠습니다.
- 현재 프로젝트 상황 브리핑혹은 발표로 진행하도록 하겠습니다.

### 컨텐츠
- 책 발표
  - [x] 케라수요일세시 Chapter 8강 발표

- 코드리뷰
  - [x] 우혁님 코드리뷰

- 프로젝트 상황 보고
  - [x] 트리케라톱스 팀
  - [x] 케라수요일세시 팀
  - [x] 1조 다음은 2조팀

- 프로젝트 진단
  - [ ] 프로젝트의 진행 상태 진단
  - [ ] 프로젝트 협업 방식 검토

- 다음주 컨콜에 대한 논의
  - [ ] 일정대로 프로젝트 발표(?)

- 기타 동아리 사안 확인
  - 00

### 마무리
정해진 기간내에 해야하는 프로젝트인 만큼 서로 다 노력해서 좋은 결과 내보도록 합시다 화이팅

**Comment by ProtossDragoon** [comment]
ㅋㅋㅋㅋㅋㅋ 진행자님 고생하셨습니다
