### ISSUE TITLE
9/28 Weekly Conference Call : OT

### ISSUE THREAD

**Issue by juhee3199** [sju-coml/SAI-2020-Team-I#6]
- [x] 장후
- [x] 주희
- [x] 영채

**Comment by ProtossDragoon** [comment]
- [x] 사랑을 담은 결석자 전화

### 시작하기 전
- [x] 녹화 환경 준비
- [x] 그룹 배정 결과 발표
- [x] 각자의 목표 공유 및 발표
  - [x] 할애할 수 있는 시간
  - [x] 자기 소개


### Github
- [x] github main README 에 링크 걸어 자랑하는 방법 보여주기 [예시 : 현직자](https://github.com/yunho0130)
- [x] 프로젝트 readme 예시 보여주기 [예시 : darknet](https://github.com/pjreddie/darknet) / [예시2 : tflite](https://github.com/yunho0130/tensorflow-lite)
- [x] issue, project 라는것이 있다는 것 보여주기
  - [x] 실제로 팀에서 공부를 할때도 github / project / issue 적극적으로 활용할 것 제안

### Notion
- [x] 그룹별  workspace 에 notion 추가 : 팀장만 초대하기, 그룹장들이 [season3 회원목록](https://docs.google.com/spreadsheets/d/12jDz8RHlNKd8z4XGIJ8RMytsvd6ShPMyk3cncZpVbhU/edit#gid=0) 에서 gmail 주소 추출, 추가하여 팀별 workspce 에 등록되도록 하기
  - [x] notion 으로 study 하는 예시 소개 : [예시1 현동팀](), [예시2 AUrix](https://www.notion.so/AUrix-Tutorial-56859ecd2dc548ec9b9df59432dfbb76), [예시3 프로젝트 자기소개같은거 보여주기](https://www.notion.so/TFlite-eaf0916af2774deb868f3d12adbd662b)

### 공지
- [x] 팀끼리 일정 잡도록 독려
  - [x] 팀끼리 모여서 무엇을 할 것인지 논의해보도록

이제 아래 내용 쭉 진행할건데, 시간이 모자라면 다음주에 계속.

**Comment by juhee3199** [comment]
### 2학기 활동계획
notion의 활동계획서 < I팀 활동 계획 > 참고하여 공지.
https://www.notion.so/Season3-2-517d5a14c14442339e8f6a56b47a75d0

- [x] 1. 전체모임
- [x] 2. 팀 스터디 개요
- [x] 3. 매주 개인 공부 개요

### 10/5일 두번째 모임에 대한 공지
- [x] 1조 발표 준비
주제: "2장 신경망의 수학적 구성요소" 
앞에서 설명한 팀 스터디 개요와 동일. 
1조 팀장인 영채님이 잘 지도(?), 진행해서 첫 발표의 좋은 사례 보여주기

**Comment by juhee3199** [comment]
### 10/5일 두번째 모임에 대한 공지
- [ ] 2조 발표 준비
주제: "2장 신경망의 수학적 구성요소" 
앞에서 설명한 팀 스터디 개요와 동일. 
2조 팀장인 영채님이 잘 지도(?), 진행해서 첫 발표의 좋은 사례 보여주기

**Comment by lunaB** [comment]
### 학기말 프로젝트 안내
- [x] 팀 프로젝트 방법
- [x] 학기말 프로젝트 계획과 방법
- [x] 프로젝트 코드리뷰 계획 설명

**Comment by ProtossDragoon** [comment]
### 과제

- [x] 그룹명 정하기
- [x] 그룹별 notion 메인 페이지 잘 꾸며 오기 
- [x] 개인 README 다듬기
- [x] 그룹1 : 책내용 발표준비 / 그룹2 : 책 외 AI관련 자유주제 10분어치 발표준비 / 그룹3 : 자율 공부
  - [x] 책 외 AI 관련 자유주제 : 아무 주제나 상관없음. SAI youtube 의 재생목록 참고할 것
  - [x] 개인이 공부해야 할 것 : **코드 업로드!** , 실습 코드 최대한 이해해서, 주석 올릴것.
