### ISSUE TITLE
10/5 Weekly Conference Call : 신경망의 수학적 구성 요소

### ISSUE THREAD

**Issue by juhee3199** [sju-coml/SAI-2020-Team-I#8]
2장 시작하기 전에: 신경망의 수학적 구성 요소  - 1조 발표

- 2.1 신경망과의 첫 만남 
- 2.2 신경망을 위한 데이터 표현 
- 2.3 신경망의 톱니바퀴: 텐서 연산 
- 2.4 신경망의 엔진: 그래디언트 기반 최적화 
- 2.5 첫 번째 예제 다시 살펴보기

**Comment by ProtossDragoon** [comment]
### 시작하기 전
- [x] 사랑을 담은 결석자 전화
- [x] 모든 팀 notion 확인
  - [x] 각 팀별 meetup 시간 정해졌는지 확인
- [x] README 네다섯개 확인
- [x] 자율적으로 팀별로 일정 잡아서 논의할 것을 권유

### 발표
- [x] group1 : 책내용 발표
- [x] group2 : 소개할만한 자유주제 10분

### 노가리
- [x] 노가리
