### ISSUE TITLE
10/26 Weekly Conference call : 신경망 시작하기

### ISSUE THREAD

**Issue by juhee3199** [sju-coml/SAI-2020-Team-I#9]
### 3장 신경망 시작하기 - 2조 발표

- 3.1 신경망의 구조 
- 3.2 케라스 소개 
- 3.3 딥러닝 컴퓨터 셋팅
- 3.4 영화 리뷰 분류: 이진 분류 예제 
- 3.5 뉴스 기사 분류: 다중 분류 문제 
- 3.6 주택 가격 예측: 회귀 문제 

### 자유발표 -  케라수요일3시 (3조)

**Comment by juhee3199** [comment]
- [ ] 자유발표 -  케라수요일3시 (3조)

**Comment by ProtossDragoon** [comment]
- [x] 사랑을 담은 결석자 전화

### 시작하기 전
- [x] 녹화 환경 준비
- [x] 다음주 인공지능 대회 관련 참석 관련 노가리
- [x] https://github.com/orgs/sju-coml/people 이거 공개좀 해줘요!
- [x] http://adm-u.intl.unist.ac.kr/%EC%B2%B4%ED%97%98%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8/u-wurf/  이런건 어때요? (조건 : 3~4학년 학부생, 겨울방학 투자)

### Notion
- [x] 그룹장 분들로부터 notion 활용중인 내용 들어보기

### 발표
- [x] 1조다음은 2조
- [x] 케라수요일3시
- [x] 간단히 보여주고자 하는 영상 (https://youtu.be/UOvPeC8WOt8) 어떻게 모델이 "예측" 을 하는가. (학습이 아님)
- [x] 제가 준비한 노트북 다들 보셨나요? 이런 내용이에요~ 소개하기
- [ ] 지금 시간 늦었는데, 다들 시간 괜찮은지 한번 여쭤보기. 다들 열심히 준비해주셔서 그런거에요~

### 공지
- [x] 이번주 국제인공지능대전 참석할 분들 확인
  - [x] 목요일 몇시에 모일지 확정하기
  - [x] 그 외에 같이 갈사람들에게도 확정된 시간 연락 돌리기
- [x] 끝나고 간단히 밥먹거나 노실분 확인
  - [x] 컨텐츠 논의 (인원수 보고 결정)
    - [x] 인원수 파악
    - [x] 가능한 최대 시간 파악. 국제인공지능대전 시작시간부터 ~ 끝나는 시간만 정하면 됨.
    - [ ] 술이 별로 안좋다?
    - [ ] 시끄러운거 싫다?
    - [ ] 돈이 3만원 이상 안들었으면 좋겠다?
       - [ ] 이 경우 예상 컨텐츠 1 : 같이 회의하기 ㅋ
       - [ ] 이 경우 예상 컨텐츠 2 : 같이 S 팀 발표 보러가서 놀래켜 드리기 ㅋ *엄청 좋아하실걸요*
- [x] 기회가 된다면, 디어 면접 본 이야기
- [x] OKR 관련 언급

**Comment by ProtossDragoon** [comment]
11:30 점심 ~
- 영채
- 문경
- 우혁
- ? 해리 (출발별개)
- 민지
- ? 윤지 (출발별개)
- ? 가영
- 주희

----

- 나영
- 성곤
- 태규
- 영민
- 현동
- 현영
